/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_ryoii_uploader_ANSIHelper */

#ifndef _Included_com_github_ryoii_uploader_ANSIHelper
#define _Included_com_github_ryoii_uploader_ANSIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_ryoii_uploader_ANSIHelper
 * Method:    enableANSI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_ryoii_uploader_ANSIHelper_enableANSI
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ryoii_uploader_ANSIHelper
 * Method:    upLine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_ryoii_uploader_ANSIHelper_upLine
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
