# nodes:
#   - username: username1
#     password: password1
#     host: host1
#     port: 22
#     origin: origin1
#     dest: dest1
#     rename: rename1
#
#   - username: your server username
#     password: your server password
#     host: your server host
#     port: sftp port
#     origin: the file will be upload
#     dest: the destination path
#     rename: (optional) the file will be rename